name: ZAP Full Scan Single Random URL

on:
  push:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Ensure CSV exists
        run: test -f data/list.csv || (echo "CSV file not found!" && exit 1)

      - name: Read a random URL from CSV
        id: get_url
        run: |
          url=$(awk -F',' 'NR>1 {print $1}' data/list.csv | shuf -n 1)
          # Add https:// if no protocol present
          if [[ ! "$url" =~ ^https?:// ]]; then
            url="https://$url"
          fi
          echo "Random URL chosen: $url"
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ steps.get_url.outputs.url }}
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: '-a -r zap-full-report.html'  # no custom rules
          allow_issue_writing: false
          artifact_name: zap-full-report-${{ github.run_id }}

      - name: Upload ZAP report artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-report-${{ github.run_id }}
          path: zap-full-report.html
